spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/config-data-movies
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 8000
